/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as ApiThinkRouteImport } from './routes/api/think'
import { Route as ApiSketchRouteImport } from './routes/api/sketch'
import { Route as ApiSentientRouteImport } from './routes/api/sentient'
import { Route as ApiExpandRouteImport } from './routes/api/expand'
import { Route as ApiClarifyRouteImport } from './routes/api/clarify'
import { Route as ApiSentientChatRouteImport } from './routes/api/sentient/chat'
import { Route as ApiNodeTableRouteImport } from './routes/api/node/table'
import { Route as ApiNodeRoadmapRouteImport } from './routes/api/node/roadmap'
import { Route as ApiNodeImageRouteImport } from './routes/api/node/image'
import { Route as ApiNodeDocRouteImport } from './routes/api/node/doc'
import { Route as ApiNodeDiagramRouteImport } from './routes/api/node/diagram'
import { Route as ApiNodeChatRouteImport } from './routes/api/node/chat'
import { Route as ApiCopilotkitSplatRouteImport } from './routes/api/copilotkit.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThinkRoute = ApiThinkRouteImport.update({
  id: '/api/think',
  path: '/api/think',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSketchRoute = ApiSketchRouteImport.update({
  id: '/api/sketch',
  path: '/api/sketch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentientRoute = ApiSentientRouteImport.update({
  id: '/api/sentient',
  path: '/api/sentient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpandRoute = ApiExpandRouteImport.update({
  id: '/api/expand',
  path: '/api/expand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClarifyRoute = ApiClarifyRouteImport.update({
  id: '/api/clarify',
  path: '/api/clarify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentientChatRoute = ApiSentientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiSentientRoute,
} as any)
const ApiNodeTableRoute = ApiNodeTableRouteImport.update({
  id: '/api/node/table',
  path: '/api/node/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodeRoadmapRoute = ApiNodeRoadmapRouteImport.update({
  id: '/api/node/roadmap',
  path: '/api/node/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodeImageRoute = ApiNodeImageRouteImport.update({
  id: '/api/node/image',
  path: '/api/node/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodeDocRoute = ApiNodeDocRouteImport.update({
  id: '/api/node/doc',
  path: '/api/node/doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodeDiagramRoute = ApiNodeDiagramRouteImport.update({
  id: '/api/node/diagram',
  path: '/api/node/diagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNodeChatRoute = ApiNodeChatRouteImport.update({
  id: '/api/node/chat',
  path: '/api/node/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotkitSplatRoute = ApiCopilotkitSplatRouteImport.update({
  id: '/api/copilotkit/$',
  path: '/api/copilotkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/expand': typeof ApiExpandRoute
  '/api/sentient': typeof ApiSentientRouteWithChildren
  '/api/sketch': typeof ApiSketchRoute
  '/api/think': typeof ApiThinkRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
  '/api/node/chat': typeof ApiNodeChatRoute
  '/api/node/diagram': typeof ApiNodeDiagramRoute
  '/api/node/doc': typeof ApiNodeDocRoute
  '/api/node/image': typeof ApiNodeImageRoute
  '/api/node/roadmap': typeof ApiNodeRoadmapRoute
  '/api/node/table': typeof ApiNodeTableRoute
  '/api/sentient/chat': typeof ApiSentientChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/expand': typeof ApiExpandRoute
  '/api/sentient': typeof ApiSentientRouteWithChildren
  '/api/sketch': typeof ApiSketchRoute
  '/api/think': typeof ApiThinkRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
  '/api/node/chat': typeof ApiNodeChatRoute
  '/api/node/diagram': typeof ApiNodeDiagramRoute
  '/api/node/doc': typeof ApiNodeDocRoute
  '/api/node/image': typeof ApiNodeImageRoute
  '/api/node/roadmap': typeof ApiNodeRoadmapRoute
  '/api/node/table': typeof ApiNodeTableRoute
  '/api/sentient/chat': typeof ApiSentientChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/clarify': typeof ApiClarifyRoute
  '/api/expand': typeof ApiExpandRoute
  '/api/sentient': typeof ApiSentientRouteWithChildren
  '/api/sketch': typeof ApiSketchRoute
  '/api/think': typeof ApiThinkRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
  '/api/node/chat': typeof ApiNodeChatRoute
  '/api/node/diagram': typeof ApiNodeDiagramRoute
  '/api/node/doc': typeof ApiNodeDocRoute
  '/api/node/image': typeof ApiNodeImageRoute
  '/api/node/roadmap': typeof ApiNodeRoadmapRoute
  '/api/node/table': typeof ApiNodeTableRoute
  '/api/sentient/chat': typeof ApiSentientChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/sitemap.xml'
    | '/api/clarify'
    | '/api/expand'
    | '/api/sentient'
    | '/api/sketch'
    | '/api/think'
    | '/api/voice'
    | '/api/copilotkit/$'
    | '/api/node/chat'
    | '/api/node/diagram'
    | '/api/node/doc'
    | '/api/node/image'
    | '/api/node/roadmap'
    | '/api/node/table'
    | '/api/sentient/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/sitemap.xml'
    | '/api/clarify'
    | '/api/expand'
    | '/api/sentient'
    | '/api/sketch'
    | '/api/think'
    | '/api/voice'
    | '/api/copilotkit/$'
    | '/api/node/chat'
    | '/api/node/diagram'
    | '/api/node/doc'
    | '/api/node/image'
    | '/api/node/roadmap'
    | '/api/node/table'
    | '/api/sentient/chat'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/sitemap.xml'
    | '/api/clarify'
    | '/api/expand'
    | '/api/sentient'
    | '/api/sketch'
    | '/api/think'
    | '/api/voice'
    | '/api/copilotkit/$'
    | '/api/node/chat'
    | '/api/node/diagram'
    | '/api/node/doc'
    | '/api/node/image'
    | '/api/node/roadmap'
    | '/api/node/table'
    | '/api/sentient/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiClarifyRoute: typeof ApiClarifyRoute
  ApiExpandRoute: typeof ApiExpandRoute
  ApiSentientRoute: typeof ApiSentientRouteWithChildren
  ApiSketchRoute: typeof ApiSketchRoute
  ApiThinkRoute: typeof ApiThinkRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  ApiCopilotkitSplatRoute: typeof ApiCopilotkitSplatRoute
  ApiNodeChatRoute: typeof ApiNodeChatRoute
  ApiNodeDiagramRoute: typeof ApiNodeDiagramRoute
  ApiNodeDocRoute: typeof ApiNodeDocRoute
  ApiNodeImageRoute: typeof ApiNodeImageRoute
  ApiNodeRoadmapRoute: typeof ApiNodeRoadmapRoute
  ApiNodeTableRoute: typeof ApiNodeTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/think': {
      id: '/api/think'
      path: '/api/think'
      fullPath: '/api/think'
      preLoaderRoute: typeof ApiThinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sketch': {
      id: '/api/sketch'
      path: '/api/sketch'
      fullPath: '/api/sketch'
      preLoaderRoute: typeof ApiSketchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentient': {
      id: '/api/sentient'
      path: '/api/sentient'
      fullPath: '/api/sentient'
      preLoaderRoute: typeof ApiSentientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expand': {
      id: '/api/expand'
      path: '/api/expand'
      fullPath: '/api/expand'
      preLoaderRoute: typeof ApiExpandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clarify': {
      id: '/api/clarify'
      path: '/api/clarify'
      fullPath: '/api/clarify'
      preLoaderRoute: typeof ApiClarifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentient/chat': {
      id: '/api/sentient/chat'
      path: '/chat'
      fullPath: '/api/sentient/chat'
      preLoaderRoute: typeof ApiSentientChatRouteImport
      parentRoute: typeof ApiSentientRoute
    }
    '/api/node/table': {
      id: '/api/node/table'
      path: '/api/node/table'
      fullPath: '/api/node/table'
      preLoaderRoute: typeof ApiNodeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/node/roadmap': {
      id: '/api/node/roadmap'
      path: '/api/node/roadmap'
      fullPath: '/api/node/roadmap'
      preLoaderRoute: typeof ApiNodeRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/node/image': {
      id: '/api/node/image'
      path: '/api/node/image'
      fullPath: '/api/node/image'
      preLoaderRoute: typeof ApiNodeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/node/doc': {
      id: '/api/node/doc'
      path: '/api/node/doc'
      fullPath: '/api/node/doc'
      preLoaderRoute: typeof ApiNodeDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/node/diagram': {
      id: '/api/node/diagram'
      path: '/api/node/diagram'
      fullPath: '/api/node/diagram'
      preLoaderRoute: typeof ApiNodeDiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/node/chat': {
      id: '/api/node/chat'
      path: '/api/node/chat'
      fullPath: '/api/node/chat'
      preLoaderRoute: typeof ApiNodeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilotkit/$': {
      id: '/api/copilotkit/$'
      path: '/api/copilotkit/$'
      fullPath: '/api/copilotkit/$'
      preLoaderRoute: typeof ApiCopilotkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSentientRouteChildren {
  ApiSentientChatRoute: typeof ApiSentientChatRoute
}

const ApiSentientRouteChildren: ApiSentientRouteChildren = {
  ApiSentientChatRoute: ApiSentientChatRoute,
}

const ApiSentientRouteWithChildren = ApiSentientRoute._addFileChildren(
  ApiSentientRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiClarifyRoute: ApiClarifyRoute,
  ApiExpandRoute: ApiExpandRoute,
  ApiSentientRoute: ApiSentientRouteWithChildren,
  ApiSketchRoute: ApiSketchRoute,
  ApiThinkRoute: ApiThinkRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  ApiCopilotkitSplatRoute: ApiCopilotkitSplatRoute,
  ApiNodeChatRoute: ApiNodeChatRoute,
  ApiNodeDiagramRoute: ApiNodeDiagramRoute,
  ApiNodeDocRoute: ApiNodeDocRoute,
  ApiNodeImageRoute: ApiNodeImageRoute,
  ApiNodeRoadmapRoute: ApiNodeRoadmapRoute,
  ApiNodeTableRoute: ApiNodeTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
